name: edq
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #firebase
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.0+1"
  cloud_firestore: ^0.16.0
  firebase_database: ^6.0.0

  http: ^0.12.2
  pattern_formatter: ^1.0.2
  flutter_spinkit: "^4.1.2"
  adaptive_dialog: ^0.9.4
  font_awesome_flutter: ^8.11.0
  badges: ^1.1.6
  geolocator: ^6.2.0
  grouped_buttons: ^1.0.4
  auto_size_text: ^2.1.0
  flutter_typeahead: ^2.0.0
  currencies: ^0.1.1

  flutter_launcher_icons: ^0.8.1
  flutter_launcher_name: "^0.0.1"
  #flutter pub run flutter_launcher_name:main
  #flutter pub run flutter_launcher_icons:main
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_native_splash: ^0.3.2

flutter_native_splash:
  color: "#ffffff"
  image: assets/edq-logo.png
  andriod: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/edq-logo-luancher.png"

flutter_launcher_name:
  name: "EDQ Book"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf

    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
